### ISSUE TITLE
Force RTV

### ISSUE THREAD

**Issue by Cads182** [wootguy/RockTheVote#1]
- Players can't re-open menu when admin forces RTV.

**Comment by wootguy** [comment]
Can't reproduce this. This is what I tried (on a listen server with 1 other player):  

1. `.forcertv`
1. Press 0 to close the menu.
1. Type `rtv`. Menu opens.
1. Pick an option, then close the menu again.
1. Type `rtv` again. Menu still opens.

Tried steps 2-5 as the other player and it worked too. Maybe there's an error in the angelscript log or console with `developer 1`?

**Comment by Tucumanos** [comment]
Seems that only happens when you force it before new map cooldown [secondsUntilVote], at first I tried alone on listen, then I tried on dedicated server with 4+ players, and still happening but now the menu re-opens after someone vote, but still can't re open the menu.
- Also I found that for some reason some maps are duplicated on nom and maplist commands.

**Comment by Cads182** [comment]
Seems that only happens when you force it before new map cooldown [secondsUntilVote], at first I tried alone on listen, then I tried on dedicated server with 4+ players, and still happening but now the menu re-opens after someone vote, but still can't re open the menu using rtv.

- Also I found that for some reason some maps are duplicated on nom and maplist commands.

**Comment by wootguy** [comment]
Alright, fixed the .forcertv bug. The duplicate maps are likely due to there being duplicate maps in your mapvote.cfg or hidden_nom_maps.txt file. Check the angelscript logs for these messages:
`[RTV] duplicate map <mapname> in list: <file path>`

Also, a map should either be in mapvote.cfg or in hidden_nom_maps.txt, but not both.

**Comment by Cads182** [comment]
Nice, I check logs but didn't got anything related, the problem was indeed duplicated maps on mapvote.cfg and hidden_nom_maps.txt, Thanks!

**Comment by wootguy** [comment]
Just added a warning message for this. If a map exists in both lists then hidden_map_lists.txt will have priority.
